name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-to-npm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: giancosta86/aurora-github/actions/publish-npm-package@v10
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

  tag-and-release:
    runs-on: ubuntu-24.04
    needs: publish-to-npm
    steps:
      - uses: actions/checkout@v4
      - uses: giancosta86/aurora-github/actions/tag-and-release@v10
