name: Publish npm package

on:
  pull_request:
    types: closed
    branches: main

  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/inject-branch-version@v5.0.0

      - uses: giancosta86/aurora-github/actions/publish-github-pages@v5.0.0

      - uses: giancosta86/aurora-github/actions/publish-npm-package@v5.0.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - uses: giancosta86/aurora-github/actions/tag-and-release@v5.0.0
